"""commented out rented at and returned

Revision ID: 0dbd3fdfb3e2
Revises: 7a65c83040e4
Create Date: 2023-12-18 00:02:10.662891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dbd3fdfb3e2'
down_revision = '7a65c83040e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rentals', schema=None) as batch_op:
        batch_op.drop_column('rented_at')
        batch_op.drop_column('returned_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rentals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('returned_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('rented_at', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
