"""added title column to rentals table

Revision ID: 10947d9f1b3d
Revises: 0dbd3fdfb3e2
Create Date: 2023-12-18 05:34:26.256753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10947d9f1b3d'
down_revision = '0dbd3fdfb3e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rentals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rentals', schema=None) as batch_op:
        batch_op.drop_column('image')
        batch_op.drop_column('price')
        batch_op.drop_column('rating')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
